### ISSUE TITLE
Modifications

### ISSUE THREAD

**Issue by jdecampos** [jdecampos/needbundle#1]
- On the Needs Creation page

**Comment by jdecampos** [comment]
Change the icons of the "needs" tabs = http://fontawesome.io/icon/bullseye/
![image](https://user-images.githubusercontent.com/14194414/27037373-11ff2680-4f88-11e7-96a1-cf213af51241.png)

![image](https://user-images.githubusercontent.com/14194414/27037403-211db384-4f88-11e7-95d9-2715d5e97a25.png)

![image](https://user-images.githubusercontent.com/14194414/27037429-344a7e60-4f88-11e7-8b00-78880113d5b9.png)

**Comment by jdecampos** [comment]
Add number of need
![image](https://user-images.githubusercontent.com/14194414/27037456-5408e3ae-4f88-11e7-8522-2769acd6aa1e.png)

**Comment by jdecampos** [comment]
In "Manage Trigger", the Publish or Unpublish button does not work
![image](https://user-images.githubusercontent.com/14194414/27037556-ac613e3e-4f88-11e7-84c9-ef86a591c2fe.png)

PS : Idem for "manage action"

**Comment by jdecampos** [comment]
In "manage action", it does not work

Step by Step : 

- Go "Manager actions"
- New
- Select need
- Add point
- When e contact : visite specific URL
- Page URL : *strategie-digitale* (https://www.kombiz.fr/blog/strategie-digitale/definissez-parcours-dachat-de-vos-visiteurs-buyers-journey.html)
- A save

Bug : The action does not appear. You have to refresh the page to see it
Bug : When I visit the page, the point is not added. I test the same configuration on "Manage actions" for points and it works

**Comment by kermorgant** [comment]
should be ok now
